### ISSUE TITLE
ros: command not foundconfig

### ISSUE THREAD

**Issue by sinkaszab** [roswell/roswell#235]
## Environment

Mac OS: 10.12.4
Emacs 25.1 (9.0)

Installed with homebrew.
Homebrew 1.1.13
Homebrew/homebrew-core (git revision 4b6f3; last commit 2017-05-01)

ros version
```sh
roswell 17.4.8.76
build with Apple LLVM version 8.1.0 (clang-802.0.42)
libcurl=7.51.0
Quicklisp=2017-03-06
Dist=2017-04-03
lispdir='/usr/local/Cellar/roswell/17.4.8.76/etc/roswell/'
configdir='/Users/[username]/.roswell/'
```

ros config
```sh
slime.version=2017.04.03
sbcl-bin.version=1.2.11
default.lisp=sbcl-bin

Possible subcommands:
set
show
```

## How to reproduce the issue

1. 1.1 Initial Recommended Setup
2. Start emacs

## Expected behavior

Have no error.

## Actual result

```
Warning (initialization): An error occurred while loading ‘/Users/[username]/.emacs.d/init.el’:

File error: Opening input file, No such file or directory, /bin/bash: ros: command not foundconfig
```

When I type:
`ros emacs` it will start an emacs, sbcl slime session...

**Comment by snmsts** [comment]
Thank you for your report.
hmm... looks roswell's setup is ok. So I guess It'll connected with emacs setup.

I'd like to ask about additional information. 
the result of ``which emacs`` and ``emacs --version`` and where it comes from (if you know about it)

I'm using osx 10.11 with emacs which installed via brew command.

**Comment by sinkaszab** [comment]
which emacs
`/usr/local/bin/emacs`

emacs --version
```sh
GNU Emacs 25.1.1
Copyright (C) 2016 Free Software Foundation, Inc.
GNU Emacs comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of GNU Emacs
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.
```

I installed emacs view homebrew also.

**Comment by snmsts** [comment]
What is happening would be there's the difference between emacs and launching SHELL's ``PATH`` environment.

hmm, I'd like to know the result of
``ros -v emacs --batch -nw --eval '(progn (princ-list (getenv "PATH")) (kill-emacs))'``
and
``echo $PATH``

**Comment by sinkaszab** [comment]
```sh
opt:verbose:1
dispatch:emacs,name=top
proc_cmd:
dispatch:/usr/local/Cellar/roswell/17.4.8.76/etc/roswell/emacs.ros,name=top
proc_cmd:
cmd_script_frontend:0
frontend:script_*:argc=8 argv[0]=/usr/local/Cellar/roswell/17.4.8.76/etc/roswell/emacs.ros
ros_script_cmd=exec ros -L sbcl-bin -m roswell -- $0 "$@"
dispatch:-L,name=top
proc_options:-L:top
set_opt(lisp)='sbcl-bin'
dispatch:-m,name=top
proc_options:-m:top
set_opt(image)='roswell'
dispatch:--,name=top
proc_options:--:top
cmd_script_frontend:1
cmd_script
get_opt(program,0)=(null)
script_:argc=9 argv[0]=--
current=(null)
set_opt(script)='"/usr/local/Cellar/roswell/17.4.8.76/etc/roswell/emacs.ros""--batch""-nw""--eval""(progn (princ-list (get-env \"PATH\")) (kilall emacs))""and""echo""/Library/Frameworks/Python.framework/Versions/3.4/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"'
cmd_run_star:1:script
,argv[0]get_opt(lisp,1)=sbcl-bin
determin_impl:sbcl-bin
get_opt(sbcl-bin.version,1)=1.2.11
set_opt(impl)='sbcl-bin/1.2.11'
set_opt(quicklisp)='/Users/[username]/.roswell/lisp/quicklisp/'
set_opt(argv0)='ros'
which cmd:command -v "ros"
which result:/usr/local/bin/ros

set_opt(wargv0)='/usr/local/bin/ros'
set_opt(homedir)='/Users/[username]/.roswell/'
set_opt(verbose)='1'
set_opt(lispdir)='/usr/local/Cellar/roswell/17.4.8.76/etc/roswell/'
get_opt(asdf.version,0)=(null)
get_opt(program,0)=(null)
set_opt(program)='(:eval"(ros:quicklisp)")'
get_opt(impl,0)=sbcl-bin/1.2.11
get_opt(help,0)=(null)
get_opt(script,0)="/usr/local/Cellar/roswell/17.4.8.76/etc/roswell/emacs.ros""--batch""-nw""--eval""(progn (princ-list (get-env \"PATH\")) (kilall emacs))""and""echo""/Library/Frameworks/Python.framework/Versions/3.4/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
get_opt(image,0)=roswell
get_opt(program,0)=(:eval"(ros:quicklisp)")
get_opt(dynamic-space-size,0)=(null)
get_opt(control-stack-size,0)=(null)
get_opt(enable-debugger,0)=(null)
get_opt(version,0)=(null)

help=nil script="/usr/local/Cellar/roswell/17.4.8.76/etc/roswell/emacs.ros""--batch""-nw""--eval""(progn (princ-list (get-env \"PATH\")) (kilall emacs))""and""echo""/Library/Frameworks/Python.framework/Versions/3.4/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
get_opt(wrap,1)=(null)
args /Users/[username]/.roswell/impls/x86-64/darwin/sbcl-bin/1.2.11/bin/sbcl --core /Users/[username]/.roswell/impls/x86-64/darwin/sbcl-bin/1.2.11/dump/roswell.core --noinform --no-sysinit --no-userinit --disable-debugger --eval (progn #-ros.init(cl:load "/usr/local/Cellar/roswell/17.4.8.76/etc/roswell/init.lisp")) --eval (ros:run '((:eval"(ros:quicklisp)")(:script "/usr/local/Cellar/roswell/17.4.8.76/etc/roswell/emacs.ros""--batch""-nw""--eval""(progn (princ-list (get-env \"PATH\")) (kilall emacs))""and""echo""/Library/Frameworks/Python.framework/Versions/3.4/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin")(:quit ())))
ROS_OPTS (("program""(:eval\"(ros:quicklisp)\")")("lispdir""/usr/local/Cellar/roswell/17.4.8.76/etc/roswell/")("verbose""1")("homedir""/Users/[username]/.roswell/")("wargv0""/usr/local/bin/ros")("argv0""ros")("quicklisp""/Users/[username]/.roswell/lisp/quicklisp/")("impl""sbcl-bin/1.2.11")("script""\"/usr/local/Cellar/roswell/17.4.8.76/etc/roswell/emacs.ros\"\"--batch\"\"-nw\"\"--eval\"\"(progn (princ-list (get-env \\\"PATH\\\")) (kilall emacs))\"\"and\"\"echo\"\"/Library/Frameworks/Python.framework/Versions/3.4/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin\"")("image""roswell")("lisp""sbcl-bin")("slime.version""2017.04.03")("sbcl-bin.version""1.2.11")("default.lisp""sbcl-bin"))
Symbol’s function definition is void: get-env
```

And sorry for incidentally closing and reopening the issue...

**Comment by snmsts** [comment]
Are you using shell extension?
command line the roswell recognized was find from 

```
get_opt(script,0)="/usr/local/Cellar/roswell/17.4.8.76/etc/roswell/emacs.ros""--batch""-nw""--eval""(progn (princ-list (get-env \"PATH\")) (kilall emacs))""and""echo""/Library/Frameworks/Python.framework/Versions/3.4/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
```

what I can feel it's different from what it should be. 


``getenv`` -> ``get-env``
``kill-emacs`` -> ``killall emacs`` ;; how come?
and later part ``""and""echo""/Library/Frameworks/Python.framework/Versions/3.4/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"``

I've never seen.

**Comment by snmsts** [comment]
It's OK if you do understand how ``kill-emacs`` becomes ``killall emacs`` on your environment,
cut it off and try the same thing.
but if not, you should review the setting first and make issue later.

**Comment by sinkaszab** [comment]
I am really sorry, I should have copy-pasted it...

result of
`ros -v emacs --batch -nw --eval '(progn (princ-list (getenv "PATH")) (kill-emacs))'`

```sh
opt:verbose:1
dispatch:emacs,name=top
proc_cmd:
dispatch:/usr/local/Cellar/roswell/17.4.8.76/etc/roswell/emacs.ros,name=top
proc_cmd:
cmd_script_frontend:0
frontend:script_*:argc=5 argv[0]=/usr/local/Cellar/roswell/17.4.8.76/etc/roswell/emacs.ros
ros_script_cmd=exec ros -L sbcl-bin -m roswell -- $0 "$@"
dispatch:-L,name=top
proc_options:-L:top
set_opt(lisp)='sbcl-bin'
dispatch:-m,name=top
proc_options:-m:top
set_opt(image)='roswell'
dispatch:--,name=top
proc_options:--:top
cmd_script_frontend:1
cmd_script
get_opt(program,0)=(null)
script_:argc=6 argv[0]=--
current=(null)
set_opt(script)='"/usr/local/Cellar/roswell/17.4.8.76/etc/roswell/emacs.ros""--batch""-nw""--eval""(progn (princ-list (getenv \"PATH\")) (kill-emacs))"'
cmd_run_star:1:script
,argv[0]get_opt(lisp,1)=sbcl-bin
determin_impl:sbcl-bin
get_opt(sbcl-bin.version,1)=1.2.11
set_opt(impl)='sbcl-bin/1.2.11'
set_opt(quicklisp)='/Users/[username]/.roswell/lisp/quicklisp/'
set_opt(argv0)='ros'
which cmd:command -v "ros"
which result:/usr/local/bin/ros

set_opt(wargv0)='/usr/local/bin/ros'
set_opt(homedir)='/Users/[username]/.roswell/'
set_opt(verbose)='1'
set_opt(lispdir)='/usr/local/Cellar/roswell/17.4.8.76/etc/roswell/'
get_opt(asdf.version,0)=(null)
get_opt(program,0)=(null)
set_opt(program)='(:eval"(ros:quicklisp)")'
get_opt(impl,0)=sbcl-bin/1.2.11
get_opt(help,0)=(null)
get_opt(script,0)="/usr/local/Cellar/roswell/17.4.8.76/etc/roswell/emacs.ros""--batch""-nw""--eval""(progn (princ-list (getenv \"PATH\")) (kill-emacs))"
get_opt(image,0)=roswell
get_opt(program,0)=(:eval"(ros:quicklisp)")
get_opt(dynamic-space-size,0)=(null)
get_opt(control-stack-size,0)=(null)
get_opt(enable-debugger,0)=(null)
get_opt(version,0)=(null)

help=nil script="/usr/local/Cellar/roswell/17.4.8.76/etc/roswell/emacs.ros""--batch""-nw""--eval""(progn (princ-list (getenv \"PATH\")) (kill-emacs))"
get_opt(wrap,1)=(null)
args /Users/[username]/.roswell/impls/x86-64/darwin/sbcl-bin/1.2.11/bin/sbcl --core /Users/[username]/.roswell/impls/x86-64/darwin/sbcl-bin/1.2.11/dump/roswell.core --noinform --no-sysinit --no-userinit --disable-debugger --eval (progn #-ros.init(cl:load "/usr/local/Cellar/roswell/17.4.8.76/etc/roswell/init.lisp")) --eval (ros:run '((:eval"(ros:quicklisp)")(:script "/usr/local/Cellar/roswell/17.4.8.76/etc/roswell/emacs.ros""--batch""-nw""--eval""(progn (princ-list (getenv \"PATH\")) (kill-emacs))")(:quit ())))
ROS_OPTS (("program""(:eval\"(ros:quicklisp)\")")("lispdir""/usr/local/Cellar/roswell/17.4.8.76/etc/roswell/")("verbose""1")("homedir""/Users/[username]/.roswell/")("wargv0""/usr/local/bin/ros")("argv0""ros")("quicklisp""/Users/[username]/.roswell/lisp/quicklisp/")("impl""sbcl-bin/1.2.11")("script""\"/usr/local/Cellar/roswell/17.4.8.76/etc/roswell/emacs.ros\"\"--batch\"\"-nw\"\"--eval\"\"(progn (princ-list (getenv \\\"PATH\\\")) (kill-emacs))\"")("image""roswell")("lisp""sbcl-bin")("slime.version""2017.04.03")("sbcl-bin.version""1.2.11")("default.lisp""sbcl-bin"))
/Library/Frameworks/Python.framework/Versions/3.4/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
```

result of
`echo $PATH`

```sh
/Library/Frameworks/Python.framework/Versions/3.4/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
```

**Comment by snmsts** [comment]
OK, Now I confirmed that shell's ``PATH`` and emacs's ``PATH`` are the same.
My guess was those are different but that assumption was false.

Then second guess for me is ``Something wrong with init file``.

so how about try
``ros emacs -q`` then type ``M-x slime`` ?

do you see it working?

**Comment by sinkaszab** [comment]
Yes, this starts an sbcl-slime session. As does `ros emacs`.

```el
(require 'package)
(setq package-archives '(("gnu" . "https://elpa.gnu.org/packages/")
                         ("melpa" . "https://melpa.org/packages/")))
(package-initialize)

(global-font-lock-mode 1)

;; Kill welcome message
(setq inhibit-startup-message t)

;; ------------------------------------
;; Setup GUI

(tool-bar-mode -1)
(menu-bar-mode -1)
(scroll-bar-mode -1)
(tooltip-mode -1)

(defalias 'yes-or-no-p 'y-or-n-p)

(set-language-environment "utf-8")
(setq default-buffer-file-coding-system 'utf-8)

(add-to-list 'default-frame-alist '(font . "Source Code Pro-14" ))

(add-to-list 'exec-path "/usr/local/bin")

;; ------------------------------------
;; Overwrite selected region

(delete-selection-mode 1)

;; ------------------------------------
;; Custom

(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(custom-safe-themes
   (quote
    ("8aebf25556399b58091e533e455dd50a6a9cba958cc4ebb0aab175863c25b9a4" "d677ef584c6dfc0697901a44b885cc18e206f05114c8a3b7fde674fce6180879" "a8245b7cc985a0610d71f9852e9f2767ad1b852c2bdea6f4aadc12cce9c4d6d0" default)))
 '(package-selected-packages
   (quote
    (ag slime solarized-theme flatui-theme projectile magit company rainbow-delimiters paganini-theme cljr-helm))))

(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )

;; ------------------------------------
;; SLIME | LISP

;; Using either or both roswell fn calls resulted in error...

;;(load (expand-file-name "~/.roswell/helper.el"))
;;(setq inferior-lisp-program "ros -Q run")

;;(setf slime-lisp-implementations
;;      `((sbcl    ("sbcl" "--dynamic-space-size" "2000"))
;;        (roswell ("ros" "-Q" "run"))))
;;(setf slime-default-lisp 'roswell)

;;(require 'slime)
;;(setq slime-net-coding-system 'utf-8-unix)
;;(prefer-coding-system 'utf-8)
;;(set-terminal-coding-system 'utf-8)
;;(slime-setup '(slime-fancy))
;;(slime)

;;(add-hook 'slime-mode-hook #'paredit-mode)

;; ------------------------------------
;; Clojure mode & Cider

(require 'clojure-mode)
(require 'clj-refactor)

(add-hook 'cider-mode-hook #'eldoc-mode)
(add-hook 'clojure-mode-hook #'paredit-mode)
(add-hook 'cider-repl-mode-hook #'paredit-mode)
(add-hook 'clojure-mode-hook #'rainbow-delimiters-mode)
(add-hook 'cider-repl-mode-hook #'rainbow-delimiters-mode)

(setq company-idle-delay nil)
(global-set-key [C-tab] #'company-complete)
(add-hook 'cider-repl-mode-hook #'company-mode)
(add-hook 'cider-mode-hook #'company-mode)

(defun my-clojure-mode-hook ()
  (clj-refactor-mode 1)
  (add-to-list 'write-file-functions 'delete-trailing-whitespace)
  (cljr-add-keybindings-with-prefix "C-c C-m"))

(add-hook 'clojure-mode-hook #'my-clojure-mode-hook)

;; ------------------------------------
;; figwheel

(setq cider-cljs-lein-repl
     "(do (require 'figwheel-sidecar.repl-api)
          (figwheel-sidecar.repl-api/start-figwheel!)
          (figwheel-sidecar.repl-api/cljs-repl))")

;; ------------------------------------

(setq cljr-suppress-middleware-warnings t)

;; ------------------------------------
;; Space correction / indentation

(global-set-key (kbd "M-SPC")
                (lambda () (interactive)
                  (setq current-prefix-arg '(-1)) ; C-u
                  (call-interactively 'cycle-spacing)))

(global-set-key (kbd "C-z") nil)

;; ------------------------------------
;; SOLARIZED THEME

;; make the fringe stand out from the background
(setq solarized-distinct-fringe-background t)

;; Don't change the font for some headings and titles
(setq solarized-use-variable-pitch nil)

;; make the modeline high contrast
(setq solarized-high-contrast-mode-line t)

;; Use less bolding
(setq solarized-use-less-bold t)

;; Use more italics
(setq solarized-use-more-italic t)

;; Use less colors for indicators such as git:gutter, flycheck and similar
(setq solarized-emphasize-indicators nil)

;; Don't change size of org-mode headlines (but keep other size-changes)
(setq solarized-scale-org-headlines nil)

;; Avoid all font-size changes
(setq solarized-height-minus-1 1.0)
(setq solarized-height-plus-1 1.0)
(setq solarized-height-plus-2 1.0)
(setq solarized-height-plus-3 1.0)
(setq solarized-height-plus-4 1.0)

(load-theme 'solarized-light t)

;; (load-theme 'paganini t)
;; (load-theme 'flatui t)

;; ------------------------------------
;; Paren mode

(require 'color)
(show-paren-mode 1)
(setq show-paren-style 'expression)

;; ------------------------------------
;; Highlight selected S-expression
(require 'paren)
(set-face-foreground 'show-paren-match nil)
(set-face-background 'show-paren-match (color-darken-name
					(face-background 'default)
					5))

;; ------------------------------------
;; Projectile

(require 'projectile)
(projectile-global-mode)

;; ------------------------------------
;; Magit

(global-set-key (kbd "C-x g") 'magit-status)
(setq magit-diff-refine-hunk t)

;; ------------------------------------
;; Switch file in buffer

(global-set-key (kbd "C-x C-b") 'buffer-menu)

;; ------------------------------------
;; ido mode

(ido-mode)
```

**Comment by snmsts** [comment]
Sorry,I miss oriented.what's the problem for now?

**Comment by snmsts** [comment]
I think It's issue for you now.If it's not roswell's issue Help yourself.

**Comment by sinkaszab** [comment]
The issue is, not starting emacs from commandline with ros results in error.

The needed init config call results in ros command not found.

But then I'll try to solve that.

**Comment by snmsts** [comment]
It was.

**Comment by nathanvy** [comment]
Hello, I have this same issue.  Are you aware of what the fix for @sinkaszab 's config file was?

**Comment by nathanvy** [comment]
Figured it out.  For anyone else with this issue, the problem was resolved by ensuring that emacs' PATH variable and exec-path variable contained /usr/local/bin which contains the roc executable.

**Comment by aesyondu** [comment]
> Figured it out. For anyone else with this issue, the problem was resolved by ensuring that emacs' PATH variable and exec-path variable contained /usr/local/bin which contains the roc executable.

I don't get it, I followed [this tutorial](https://github.com/roswell/roswell/wiki/Initial-Recommended-Setup) and added the two lines in ~/.emacs.d/init.el. Since exec-path was mentioned I added it just in case. But emacs still throws an error when started from Spotlight. It doesn't though when run from cli `emacs` or `ros emacs`

```emacs
(add-to-list 'exec-path "/usr/local/bin")
(load (expand-file-name "~/.roswell/helper.el"))
(setq inferior-lisp-program "ros -Q run")
```
